### ISSUE TITLE
Link for regexp broken

### ISSUE THREAD

**Issue by dvanic** [swcarpentry/shell-novice#295] opened 2016-01-31 03:49 UTC
Hi! The link to ["if you want to do complex searches, please look at the lesson on our website."](http://software-carpentry.org/v4/regexp/index.html) is broken, given a 404 error. Where should the link be pointing to?

**Comment by gdevenyi** [comment] 2016-01-31 20:11
Looks like our regex lesson has been depreciated, will need to find the archived version

**Comment by gdevenyi** [comment] 2016-01-31 21:01
Duplicate of #279

**Closed by gdevenyi** 2016-01-31 21:01 UTC
