### ISSUE TITLE
`ls -F` never fully explained

### ISSUE THREAD

**Issue by hollybik** [swcarpentry/shell-novice#901] opened 2019-01-18 15:45 UTC
`ls -F` is never fully explained (and the man page for ls doesn't provide helpful information on what this flag is doing in case users are trying to figure it out on their own). Issue #846 has raised this same point.

**Comment by gcapes** [comment] 2019-01-21 11:59
Closing as duplicate of #846. Please discuss on that issue.

**Closed by gcapes** 2019-01-21 11:59 UTC
Labels: status:duplicate, type:clarification
