### ISSUE TITLE
Make serve fail

### ISSUE THREAD

**Issue by bagustris** [swcarpentry/shell-novice#731] opened 2018-03-08 07:29 UTC
I run `make serve` to build site locally, but it failed today (it works on other lessons). Here are the details of output.

     jekyll serve
     Configuration file: /tmp/shell-novice/_config.yml
            Source: /tmp/shell-novice
       Destination: /tmp/shell-novice/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
       Liquid Exception: Liquid syntax error: Unknown tag 'link' in _includes/navbar.html, included in 
       _layouts/base.html
      jekyll 3.0.1 | Error:  Liquid syntax error: Unknown tag 'link'
     Makefile:21: recipe for target 'serve' failed
     make: *** [serve] Error 1`

**Comment by rgaiacs** [comment] 2018-03-08 11:20
Please update your Jekyll installation to 3.2 or higher. `link` was introduced in 3.2.0, see [the release note](https://jekyllrb.com/news/2016/07/26/jekyll-3-2-0-released/). From August 23, 2016 GitHub Pages uses Jekyll 3.2, see [this blog post](https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2), so `link` is available to use in our current workflow.

I'm closing this as not a bug and as duplicated of https://github.com/swcarpentry/lesson-example/issues/143. Thanks for the report!

**Closed by rgaiacs** 2018-03-08 11:20 UTC
