### ISSUE TITLE
ls --help issue in Mac OS (suggestion for lesson clarification)

### ISSUE THREAD

**Issue by boryanakis** [swcarpentry/shell-novice#719] opened 2018-02-26 16:37 UTC
As part of the instructor checkout, I would like to offer a suggestion for section 2 (_Navigating Files and Directories_). The first time we encounter "ls --help" in the lesson, Mac users see an error message. I think it would be good to have a short note under the command in the lesson that says something to the effect of:

**NOTE**: While "ls --help" will work on Windows, the command returns an error on Mac computers. There are two ways for Mac users to get around this: 
1. You can type "man ls" into Google, and look at the first result the search engine returns. "man" is shorthand for manual, and it will display the manual of the ls command. This workaround requires that you look for the information outside of the terminal environment.
2. You can type "man ls" into your terminal. That will bring up a page with the manual of the ls command. You can use the up/down arrow to scroll through the manual, and when you are done reading it, you can press "q" to exit this screen and return to your previous terminal activities. This workaround does not require you to exit the terminal environment to find the necessary information.

I am sure that others can improve on my wording but I think it would be useful for beginners to not encounter this weird issue that early into the lesson.

**Comment by rgaiacs** [comment] 2018-02-26 17:20
Hi @boryanakis, Thanks for the issue and the suggestion. This is a long issue that we have because most Linux distributions and Git for Windows uses the GNU Project implementation of the command line and macOS uses the (Unix) Bell Labs/ implementation. The implementation differs in "minor" points but one is that some commands have `--help` or `-h` as flags but others don't and this isn't uniform across GNU vs [BSD](https://en.wikipedia.org/wiki/Berkeley_Software_Distribution), in other words some commands have `--help` in the GNU implementation but not at the BSD when the opposite happens for another command.

The Unix-like way to ask for help is `man` but Git for Windows doesn't have the manpages which creates a problem for our Windows users. This is the reason that we use `--help`. Also, was proposed to use "Google 'man ls'" but some instructors want to stay in the terminal for the case of users using a remote machine, which is a interesting case because "Google 'man ls'" could return the wrong implementation that you have installed.

I'm closing this as a duplicate of #708. Since it is the only option that would work for now.

**Closed by rgaiacs** 2018-02-26 17:20 UTC
